Console.WriteLine("Hello World");
string myName = "BHARATH";
int myAge = 18;
bool isMale = true;
Console.WriteLine("BHARATH'S AGE IS "+myAge);
Console.WriteLine("BHARATH'S NAME IS " + myName);
Console.WriteLine(isMale);
byte age = 127;
short myfriends = 21124;
float pi = 3.14f;
long PHONENUMBER = 12345321;
Decimal NOICE = 123.3m;
Console.WriteLine(NOICE);
string dawg;
dawg = "Snoop dog";
dawg = "German";
Console.WriteLine($"my pet is {dawg}");
dawg = "Nigga";
Console.WriteLine($"my pet is {dawg}");
